version: '3'

networks: 
  ci_net:

volumes:
  nexus_data:
  jenkins_data:

services: 

  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "127.0.0.1:8081:8081"
    networks: 
      - ci_net
    environment: 
      - JAVA_MIN_MEM=256m
      - JAVA_MAX_MEM=1200m

  jenkins:
    image: rgielen/jenkins-training
    restart: always
    volumes:
      - jenkins_data:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:9090:8080"
    networks: 
      - ci_net
